---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-web-hello-world
  labels:
    app.kubernetes.io/name:  hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name:  hello-world
  template:
    metadata:
      labels:
        app.kubernetes.io/name:  hello-world
    spec:
      containers:
      - name: go-web-hello-world
        image: wingasun/go-web-hello-world:v0.1
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  labels:
    name: hello-world-service
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 31080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name:  hello-world
